#!/usr/bin/perl
#
# Magic markers:
#%# family=auto
#%# capabilities=autoconf

my $ret = undef;

if (! eval "require LWP::UserAgent;")
{
	$ret = "LWP::UserAgent not found";
}

my @URLS = exists $ENV{'urls'} ? split(' ', $ENV{'urls'}) : ("http://127.0.0.1:%d/status");
my @PORTS = exists $ENV{'ports'} ? split(' ', $ENV{'ports'}) : (80);

if ( defined $ARGV[0] and $ARGV[0] eq "autoconf" )
{
	if ($ret)
	{
		print "no ($ret)\n";
		exit 1;
	}

	my $ua = LWP::UserAgent->new(timeout => 30);

	my @badports;
	for (my $i=0; $i <= $#URLS; $i++) {
		my $url = "http://localhost:".$PORTS[$i]."/status-".$URLS[$i];
		print "$url\n";
		my $response = $ua->request(HTTP::Request->new('GET',$url));
		push @badports, $port unless $response->is_success and $response->content =~ /^accepted conn:/im;
	}

	if (@badports) {
		print "no (phpfpm-status)\n";
		exit 1;
	} else {
		print "yes\n";
		exit 0;
	}
}

if ( defined $ARGV[0] and $ARGV[0] eq "config" )
{
	print('graph_title PHP5-FPM Status
graph_args --base 1024 -l 0
graph_vlabel Connections
graph_category PHP
graph_order active idle total
graph_info Plugin created by TJ Stein
active.label Active
active.draw AREA
idle.label Idle
idle.draw STACK
total.label Total
total.draw LINE1
');

	exit 0;
}

$all_idle = 0;
$all_active = 0;
$all_total = 0;

for (my $i=0; $i <= $#URLS; $i++) 
{
    my $ua = LWP::UserAgent->new(timeout => 30);
	my $url = "http://localhost:".$PORTS[$i]."/status-".$URLS[$i];
    my $response = $ua->request(HTTP::Request->new('GET',$url));

	if ($response->content =~ /idle processes:\s+([0-9\.]+)/im) {
		$all_idle += $1;
    }
	if ($response->content =~ /active processes:\s+([0-9\.]+)/im) {
		$all_ative += $1;	
    }
	if ($response->content =~ /total processes:\s+([0-9\.]+)/im) {
		$all_total += $1;
    }
}

print "idle.value $all_idle\n";
print "active.value $all_ative\n";
print "total.value $all_total\n";

# vim:syntax=perl
